name: Python Code Runner

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  run_python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9 # Specify the desired Python version

      - name: Determine folder from JSON file
        id: get_folder
        run: |
          folder=$(jq -r .folder .github/execute-python.json)
          echo "::set-output name=folder::$folder"
        shell: bash

      - name: Set folder
        run: |
          folder="${{ steps.get_folder.outputs.folder }}"
          cd $folder
      - name: build python env
        run: python -m venv venv

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: run main.py in $folder
        run: python main.py
